### ISSUE TITLE
Create pages in sections

### ISSUE THREAD

**Issue by moraisandreua** [ImajinDevon/GalaxyShop#1]
can I create pages is different sections? 

another thing, the documentation page is not working.

**Comment by ImajinDevon** [comment]
Yeah, just set the opens key in the category you wish.

**Comment by ImajinDevon** [comment]
```yml
# Example code for pages
shop:
  title: "Shop"
  rows: 3

  9:
    type: grass block
    name: "&aBlocks"
    opens: blocks
    
blocks:
  title: "&aBlocks page 1"
  rows: 1
  1:
    type: arrow
    name: "next page"
    opens: "blocks2"

blocks2:
  title: "&aBlocks page 1"
  rows: 1
```
